### ISSUE TITLE
Missing resource pack

### ISSUE THREAD

**Issue by GiuniGiorgio01** [GenerationsMod/Generations-Core#48]
The mod is correctly loaded, but when I go to the resource packs, it is not showing...
I'm using the latest release of Generations core and Cobblemon 1.4.1

**Comment by Waterpicker** [comment]
Are you running shaders?
Due to how iris highjacks the entire minecraft rendering pipeline, our renderer like any custom non vanlla rendering effect will simply not show.

**Comment by GiuniGiorgio01** [comment]
Yeah, i do run shaders, I'll try again by disabling them

**Comment by GiuniGiorgio01** [comment]
I've removed the Iris shaders and bsl shaders, now I do visualize the mod blocks but the pokemon are still blocky

**Comment by Waterpicker** [comment]
Oh! That's because you need to download seperate resource packs. The pokemon models are so bulky that we can't ship them with the mod. Mod hosting sites like modrinth have a limit.

**Comment by GiuniGiorgio01** [comment]
Ok, where do I find the separate resource pack then? 


Thank you for your patience 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

**Comment by Waterpicker** [comment]
Packs and here is the cureseforge page for the Generation team's page and thus projects which includes the resource packs. https://www.curseforge.com/members/generations/projects

**Comment by Waterpicker** [comment]
There is a corresponding modrinth counterpart as well if that's your preference.

**Comment by GiuniGiorgio01** [comment]
Thank you very much for your help ♥️

**Comment by GiuniGiorgio01** [comment]
Solved
